apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: goof
  title: NPM Goof # optional, human readable component name
  description: Goof is my first Backstage catalog item.
  annotations:
    github.com/project-slug: ksuzy31/goof
spec:
  type: service
  owner: user:ksuzy31
  lifecycle: experimental
