name: Snyk container workflow
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Snyk container test 
      run: snyk container test node:14.18.1 --file=Dockerfile --sarif-file-output=snyk-container.sarif --app-vulns --nested-jars-depth=5
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: install snyk-to-html
      run: |
       # Install the Snyk JSON to HTML Mapper using npm
        npm install snyk-to-html -g
               # Convert JSON output from `snyk test --json` into a static HTML
        snyk container test node:14.18.1 --file=Dockerfile --json --app-vulns --nested-jars-depth=5 | snyk-to-html -o result.html
        continue-on-error: true
        mkdir downloads
        cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads

      # save the HTML in the artifact
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: downloads
    - name: Upload results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk-container.sarif
