
name: Jira Sync
on:
  issues:
    types: [opened, closed, labeled, unlabeled, reopened]
  issue_comment:
    types: [created, edited, deleted]
jobs:
  sync:
    name: Sync Items
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github Issues to Jira
        uses: jordansilva/github-action-issue-to-jira@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          jiraHost: ${{ secrets.JIRA_HOST }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }} # See https://id.atlassian.com/manage/api-tokens
          project: #CLEAN
